//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-IMENS42P\\MSSQLSERVER01;Initial Catalog=QuanLyTro;Persist Secur" +
            "ity Info=True;User ID=sa;Password=sapassword")]
        public string QuanLyTroConnectionString {
            get {
                return ((string)(this["QuanLyTroConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HV7HL4N\\SQLEXPRESS;Initial Catalog=QuanLyPhongTro;User ID=sa;" +
            "Password=sapassword")]
        public string QuanLyPhongTroConnectionString {
            get {
                return ((string)(this["QuanLyPhongTroConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HV7HL4N\\SQLEXPRESS;Initial Catalog=QuanLyTro23Thang6;User ID=" +
            "sa;Password=sapassword")]
        public string QuanLyTro23Thang6ConnectionString {
            get {
                return ((string)(this["QuanLyTro23Thang6ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HV7HL4N\\SQLEXPRESS;Initial Catalog=QuanLyTro25Thang6;User ID=" +
            "sa;Password=sapassword")]
        public string QuanLyTro25Thang6ConnectionString {
            get {
                return ((string)(this["QuanLyTro25Thang6ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HV7HL4N\\SQLEXPRESS;Initial Catalog=QuanLyTro27Thang6;User ID=" +
            "sa;Password=sapassword")]
        public string QuanLyTro27Thang6ConnectionString {
            get {
                return ((string)(this["QuanLyTro27Thang6ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-8S5FT2K7;Initial Catalog=QuanLyTro;Integrated Security=True")]
        public string QuanLyTroConnectionString1 {
            get {
                return ((string)(this["QuanLyTroConnectionString1"]));
            }
        }
    }
}
