#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyTro")]
	public partial class QLyTroDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblChuTro(tblChuTro instance);
    partial void UpdatetblChuTro(tblChuTro instance);
    partial void DeletetblChuTro(tblChuTro instance);
    partial void InserttblPhong(tblPhong instance);
    partial void UpdatetblPhong(tblPhong instance);
    partial void DeletetblPhong(tblPhong instance);
    partial void InserttblSinhVien(tblSinhVien instance);
    partial void UpdatetblSinhVien(tblSinhVien instance);
    partial void DeletetblSinhVien(tblSinhVien instance);
    #endregion
		
		public QLyTroDataContext() : 
				base(global::QuanLyPhongTro.Properties.Settings.Default.QuanLyTroConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLyTroDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLyTroDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLyTroDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLyTroDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblChuTro> tblChuTros
		{
			get
			{
				return this.GetTable<tblChuTro>();
			}
		}
		
		public System.Data.Linq.Table<tblPhong> tblPhongs
		{
			get
			{
				return this.GetTable<tblPhong>();
			}
		}
		
		public System.Data.Linq.Table<tblSinhVien> tblSinhViens
		{
			get
			{
				return this.GetTable<tblSinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChuTro")]
	public partial class tblChuTro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDChuTro;
		
		private string _TenChuTro;
		
		private string _CMNDChuTro;
		
		private string _DiaChiChuTro;
		
		private int _SDTChuTro;
		
		private string _EmailChuTro;
		
		private string _TrangThaiChoThue;
		
		private string _Pass;
		
		private EntitySet<tblPhong> _tblPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChuTroChanging(string value);
    partial void OnIDChuTroChanged();
    partial void OnTenChuTroChanging(string value);
    partial void OnTenChuTroChanged();
    partial void OnCMNDChuTroChanging(string value);
    partial void OnCMNDChuTroChanged();
    partial void OnDiaChiChuTroChanging(string value);
    partial void OnDiaChiChuTroChanged();
    partial void OnSDTChuTroChanging(int value);
    partial void OnSDTChuTroChanged();
    partial void OnEmailChuTroChanging(string value);
    partial void OnEmailChuTroChanged();
    partial void OnTrangThaiChoThueChanging(string value);
    partial void OnTrangThaiChoThueChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    #endregion
		
		public tblChuTro()
		{
			this._tblPhongs = new EntitySet<tblPhong>(new Action<tblPhong>(this.attach_tblPhongs), new Action<tblPhong>(this.detach_tblPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChuTro", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDChuTro
		{
			get
			{
				return this._IDChuTro;
			}
			set
			{
				if ((this._IDChuTro != value))
				{
					this.OnIDChuTroChanging(value);
					this.SendPropertyChanging();
					this._IDChuTro = value;
					this.SendPropertyChanged("IDChuTro");
					this.OnIDChuTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuTro", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenChuTro
		{
			get
			{
				return this._TenChuTro;
			}
			set
			{
				if ((this._TenChuTro != value))
				{
					this.OnTenChuTroChanging(value);
					this.SendPropertyChanging();
					this._TenChuTro = value;
					this.SendPropertyChanged("TenChuTro");
					this.OnTenChuTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMNDChuTro", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string CMNDChuTro
		{
			get
			{
				return this._CMNDChuTro;
			}
			set
			{
				if ((this._CMNDChuTro != value))
				{
					this.OnCMNDChuTroChanging(value);
					this.SendPropertyChanging();
					this._CMNDChuTro = value;
					this.SendPropertyChanged("CMNDChuTro");
					this.OnCMNDChuTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiChuTro", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiaChiChuTro
		{
			get
			{
				return this._DiaChiChuTro;
			}
			set
			{
				if ((this._DiaChiChuTro != value))
				{
					this.OnDiaChiChuTroChanging(value);
					this.SendPropertyChanging();
					this._DiaChiChuTro = value;
					this.SendPropertyChanged("DiaChiChuTro");
					this.OnDiaChiChuTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTChuTro", DbType="Int NOT NULL")]
		public int SDTChuTro
		{
			get
			{
				return this._SDTChuTro;
			}
			set
			{
				if ((this._SDTChuTro != value))
				{
					this.OnSDTChuTroChanging(value);
					this.SendPropertyChanging();
					this._SDTChuTro = value;
					this.SendPropertyChanged("SDTChuTro");
					this.OnSDTChuTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailChuTro", DbType="NVarChar(100)")]
		public string EmailChuTro
		{
			get
			{
				return this._EmailChuTro;
			}
			set
			{
				if ((this._EmailChuTro != value))
				{
					this.OnEmailChuTroChanging(value);
					this.SendPropertyChanging();
					this._EmailChuTro = value;
					this.SendPropertyChanged("EmailChuTro");
					this.OnEmailChuTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiChoThue", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TrangThaiChoThue
		{
			get
			{
				return this._TrangThaiChoThue;
			}
			set
			{
				if ((this._TrangThaiChoThue != value))
				{
					this.OnTrangThaiChoThueChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiChoThue = value;
					this.SendPropertyChanged("TrangThaiChoThue");
					this.OnTrangThaiChoThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(20)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChuTro_tblPhong", Storage="_tblPhongs", ThisKey="IDChuTro", OtherKey="IDChuTro")]
		public EntitySet<tblPhong> tblPhongs
		{
			get
			{
				return this._tblPhongs;
			}
			set
			{
				this._tblPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhongs(tblPhong entity)
		{
			this.SendPropertyChanging();
			entity.tblChuTro = this;
		}
		
		private void detach_tblPhongs(tblPhong entity)
		{
			this.SendPropertyChanging();
			entity.tblChuTro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhong")]
	public partial class tblPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDPhong;
		
		private string _TrangThaiPhong;
		
		private decimal _GiaPhong;
		
		private int _SoLuongSVSong;
		
		private string _TenPhong;
		
		private string _IDChuTro;
		
		private System.Nullable<System.DateTime> _NgayBatDau;
		
		private EntitySet<tblSinhVien> _tblSinhViens;
		
		private EntityRef<tblChuTro> _tblChuTro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPhongChanging(string value);
    partial void OnIDPhongChanged();
    partial void OnTrangThaiPhongChanging(string value);
    partial void OnTrangThaiPhongChanged();
    partial void OnGiaPhongChanging(decimal value);
    partial void OnGiaPhongChanged();
    partial void OnSoLuongSVSongChanging(int value);
    partial void OnSoLuongSVSongChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    partial void OnIDChuTroChanging(string value);
    partial void OnIDChuTroChanged();
    partial void OnNgayBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBatDauChanged();
    #endregion
		
		public tblPhong()
		{
			this._tblSinhViens = new EntitySet<tblSinhVien>(new Action<tblSinhVien>(this.attach_tblSinhViens), new Action<tblSinhVien>(this.detach_tblSinhViens));
			this._tblChuTro = default(EntityRef<tblChuTro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhong", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDPhong
		{
			get
			{
				return this._IDPhong;
			}
			set
			{
				if ((this._IDPhong != value))
				{
					this.OnIDPhongChanging(value);
					this.SendPropertyChanging();
					this._IDPhong = value;
					this.SendPropertyChanged("IDPhong");
					this.OnIDPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiPhong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TrangThaiPhong
		{
			get
			{
				return this._TrangThaiPhong;
			}
			set
			{
				if ((this._TrangThaiPhong != value))
				{
					this.OnTrangThaiPhongChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiPhong = value;
					this.SendPropertyChanged("TrangThaiPhong");
					this.OnTrangThaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaPhong", DbType="Money NOT NULL")]
		public decimal GiaPhong
		{
			get
			{
				return this._GiaPhong;
			}
			set
			{
				if ((this._GiaPhong != value))
				{
					this.OnGiaPhongChanging(value);
					this.SendPropertyChanging();
					this._GiaPhong = value;
					this.SendPropertyChanged("GiaPhong");
					this.OnGiaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongSVSong", DbType="Int NOT NULL")]
		public int SoLuongSVSong
		{
			get
			{
				return this._SoLuongSVSong;
			}
			set
			{
				if ((this._SoLuongSVSong != value))
				{
					this.OnSoLuongSVSongChanging(value);
					this.SendPropertyChanging();
					this._SoLuongSVSong = value;
					this.SendPropertyChanged("SoLuongSVSong");
					this.OnSoLuongSVSongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChuTro", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string IDChuTro
		{
			get
			{
				return this._IDChuTro;
			}
			set
			{
				if ((this._IDChuTro != value))
				{
					if (this._tblChuTro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChuTroChanging(value);
					this.SendPropertyChanging();
					this._IDChuTro = value;
					this.SendPropertyChanged("IDChuTro");
					this.OnIDChuTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhong_tblSinhVien", Storage="_tblSinhViens", ThisKey="IDPhong", OtherKey="IDPhong")]
		public EntitySet<tblSinhVien> tblSinhViens
		{
			get
			{
				return this._tblSinhViens;
			}
			set
			{
				this._tblSinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChuTro_tblPhong", Storage="_tblChuTro", ThisKey="IDChuTro", OtherKey="IDChuTro", IsForeignKey=true)]
		public tblChuTro tblChuTro
		{
			get
			{
				return this._tblChuTro.Entity;
			}
			set
			{
				tblChuTro previousValue = this._tblChuTro.Entity;
				if (((previousValue != value) 
							|| (this._tblChuTro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblChuTro.Entity = null;
						previousValue.tblPhongs.Remove(this);
					}
					this._tblChuTro.Entity = value;
					if ((value != null))
					{
						value.tblPhongs.Add(this);
						this._IDChuTro = value.IDChuTro;
					}
					else
					{
						this._IDChuTro = default(string);
					}
					this.SendPropertyChanged("tblChuTro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSinhViens(tblSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tblPhong = this;
		}
		
		private void detach_tblSinhViens(tblSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tblPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSinhVien")]
	public partial class tblSinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSSV;
		
		private string _TenSV;
		
		private string _QueQuanSV;
		
		private string _SDTSV;
		
		private System.Nullable<System.DateTime> _NamSinhSV;
		
		private string _TruongHoc;
		
		private string _KhoaSV;
		
		private string _IDPhong;
		
		private EntityRef<tblPhong> _tblPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OnTenSVChanging(string value);
    partial void OnTenSVChanged();
    partial void OnQueQuanSVChanging(string value);
    partial void OnQueQuanSVChanged();
    partial void OnSDTSVChanging(string value);
    partial void OnSDTSVChanged();
    partial void OnNamSinhSVChanging(System.Nullable<System.DateTime> value);
    partial void OnNamSinhSVChanged();
    partial void OnTruongHocChanging(string value);
    partial void OnTruongHocChanged();
    partial void OnKhoaSVChanging(string value);
    partial void OnKhoaSVChanged();
    partial void OnIDPhongChanging(string value);
    partial void OnIDPhongChanged();
    #endregion
		
		public tblSinhVien()
		{
			this._tblPhong = default(EntityRef<tblPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenSV
		{
			get
			{
				return this._TenSV;
			}
			set
			{
				if ((this._TenSV != value))
				{
					this.OnTenSVChanging(value);
					this.SendPropertyChanging();
					this._TenSV = value;
					this.SendPropertyChanged("TenSV");
					this.OnTenSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuanSV", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string QueQuanSV
		{
			get
			{
				return this._QueQuanSV;
			}
			set
			{
				if ((this._QueQuanSV != value))
				{
					this.OnQueQuanSVChanging(value);
					this.SendPropertyChanging();
					this._QueQuanSV = value;
					this.SendPropertyChanged("QueQuanSV");
					this.OnQueQuanSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SDTSV
		{
			get
			{
				return this._SDTSV;
			}
			set
			{
				if ((this._SDTSV != value))
				{
					this.OnSDTSVChanging(value);
					this.SendPropertyChanging();
					this._SDTSV = value;
					this.SendPropertyChanged("SDTSV");
					this.OnSDTSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinhSV", DbType="Date")]
		public System.Nullable<System.DateTime> NamSinhSV
		{
			get
			{
				return this._NamSinhSV;
			}
			set
			{
				if ((this._NamSinhSV != value))
				{
					this.OnNamSinhSVChanging(value);
					this.SendPropertyChanging();
					this._NamSinhSV = value;
					this.SendPropertyChanged("NamSinhSV");
					this.OnNamSinhSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongHoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TruongHoc
		{
			get
			{
				return this._TruongHoc;
			}
			set
			{
				if ((this._TruongHoc != value))
				{
					this.OnTruongHocChanging(value);
					this.SendPropertyChanging();
					this._TruongHoc = value;
					this.SendPropertyChanged("TruongHoc");
					this.OnTruongHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoaSV", DbType="NVarChar(20)")]
		public string KhoaSV
		{
			get
			{
				return this._KhoaSV;
			}
			set
			{
				if ((this._KhoaSV != value))
				{
					this.OnKhoaSVChanging(value);
					this.SendPropertyChanging();
					this._KhoaSV = value;
					this.SendPropertyChanged("KhoaSV");
					this.OnKhoaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhong", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string IDPhong
		{
			get
			{
				return this._IDPhong;
			}
			set
			{
				if ((this._IDPhong != value))
				{
					if (this._tblPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPhongChanging(value);
					this.SendPropertyChanging();
					this._IDPhong = value;
					this.SendPropertyChanged("IDPhong");
					this.OnIDPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhong_tblSinhVien", Storage="_tblPhong", ThisKey="IDPhong", OtherKey="IDPhong", IsForeignKey=true)]
		public tblPhong tblPhong
		{
			get
			{
				return this._tblPhong.Entity;
			}
			set
			{
				tblPhong previousValue = this._tblPhong.Entity;
				if (((previousValue != value) 
							|| (this._tblPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPhong.Entity = null;
						previousValue.tblSinhViens.Remove(this);
					}
					this._tblPhong.Entity = value;
					if ((value != null))
					{
						value.tblSinhViens.Add(this);
						this._IDPhong = value.IDPhong;
					}
					else
					{
						this._IDPhong = default(string);
					}
					this.SendPropertyChanged("tblPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
